######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 16 14:46:42 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += .

# Input
SOURCES += src/main.cpp
