time = Time.new

print "setDateAndTime" + "\t.\t.\t.\t.\t.\t.\t.\t.\t.\t.\t.\t" + "OK Now date #{time}" + "\n"
print "setHolidaySchedule" + "\t.\t.\t.\t.\t.\t.\t.\t.\t.\t.\t" + "OK List upload" + "\n"
print "setAnnualTariffSchedule" + "\t.\t.\t.\t.\t.\t.\t.\t.\t.\t" + "OK List upload" + "\n"
print "setAveragePower4LoadControl" + "\t.\t.\t.\t.\t.\t.\t.\t.\t" + "OK 1kWt" + "\n"
print "setModesOfPulseOutputs" + "\t.\t.\t.\t.\t.\t.\t.\t.\t.\t" + "OK" + "\n"
print "setVerification/Telemetry" + "\t.\t.\t.\t.\t.\t.\t.\t.\t" + "OK" + "\n"
print "setAutomaticLoadControl" + "\t.\t.\t.\t.\t.\t.\t.\t.\t.\t" + "OK setAutomatic is ON" + "\n"
print "setCalibration" + "\t.\t.\t.\t.\t.\t.\t.\t.\t.\t.\t.\t" + "OK" + "\n"
print "setDisplayMode" + "\t.\t.\t.\t.\t.\t.\t.\t.\t.\t.\t.\t" + "OK" + "\n"
print "setListPasswd" + "\t.\t.\t.\t.\t.\t.\t.\t.\t.\t.\t.\t" + "OK List upload" + "\n"
sleep 3
time = Time.new
print "getActiveAndReactiveEnergy4TariffsAndTotal" + "\t.\t.\t.\t.\t" + "12KwT" + "\n"
print "getCurrentActivePowerPerPhaseAndTotalValue" + "\t.\t.\t.\t.\t" + "5KwT" + "\n"
print "getCurrentReactivePowerForEachPhaseAndTotalValue" + "\t.\t.\t" + "3KwT" + "\n"
print "getDateAndTime" + "\t.\t.\t.\t.\t.\t.\t.\t.\t.\t.\t.\t" + "#{time}" + "\n"
print "getFrequency" + "\t.\t.\t.\t.\t.\t.\t.\t.\t.\t.\t.\t" + "50 H" + "\n"
print "getNetworkAddressCounter" + "\t.\t.\t.\t.\t.\t.\t.\t.\t" + "192.168.43.249" + "\n"
print "getReactivePowerUnderAllTariffs" + "\t.\t.\t.\t.\t.\t.\t.\t" + "1.5KwT" + "\n"
print "getFullPowerCurrentOfEachPhaseAndTotalValue" + "\t.\t.\t.\t.\t" + "15KwT" + "\n"
print "getIdentifierOfMetrologicalSoftware" + "\t.\t.\t.\t.\t.\t.\t" + "ERV415ERG5" + "\n"
print "getVersionOfSoftware" + "\t.\t.\t.\t.\t.\t.\t.\t.\t.\t" + "v 1.1" + "\n"
print "getVoltageAndCurrentForEachPhase" + "\t.\t.\t.\t.\t.\t.\t" + "220" + "\n"
